CREATE DATABASE ARTICULOS_FACTURA

CREATE TABLE ARTICULOS (
ID_ARTICULO INT IDENTITY (1,1) PRIMARY KEY,
NOMBRE NVARCHAR (100)
)

CREATE TABLE FORMAS_PAGOS (
ID_FORMA_PAGO INT IDENTITY (1,1) PRIMARY KEY,
NOMBRE NVARCHAR (100)
)

CREATE TABLE DETALLES_FACTURAS (
ID_DETALLE_FACTURA INT IDENTITY (1,1) PRIMARY KEY,
NRO_FACTURA INT NOT NULL,
ID_ARTICULO INT NOT NULL,
CANTIDAD INT NOT NULL
CONSTRAINT FK_DETALLES_FACTURAS_FACTURAS FOREIGN KEY (NRO_FACTURA) 
REFERENCES FACTURAS (NRO_FACTURA),
CONSTRAINT FK_DETALLES_FACTURAS_ARTICULOS FOREIGN KEY (ID_ARTICULO) 
REFERENCES ARTICULOS (ID_ARTICULO)
)

CREATE TABLE FACTURAS (
NRO_FACTURA INT IDENTITY (1,1) PRIMARY KEY,
FECHA DATE NOT NULL,
ID_FORMA_PAGO INT NOT NULL,
CLIENTE NVARCHAR (100) NOT NULL
CONSTRAINT FK_FACTURAS_FORMAS_PAGOS FOREIGN KEY (ID_FORMA_PAGO) 
REFERENCES FORMAS_PAGOS (ID_FORMA_PAGO)
)

ALTER TABLE DETALLES_FACTURAS ADD PRECIO FLOAT NOT NULL
ALTER TABLE ARTICULOS ADD PRECIO_UNITARIO FLOAT NOT NULL

INSERT INTO FORMAS_PAGOS (NOMBRE) VALUES ('EFECTIVO'), ('TRANSFERENCIA'), ('TARJETA DEBITO'), ('TARJETA CREDITO');
INSERT INTO ARTICULOS (NOMBRE, PRECIO_UNITARIO) VALUES ('HARINA', 1800), ('AZUCAR', 2000), ('YERBA', 2900), ('PAN', 800), ('FIDEOS', 2100), ('ARROZ',1300), ('POLENTA', 1900), ('MAIZENA', 1700);

SELECT * FROM ARTICULOS